### ISSUE TITLE
keycloak theme: align with dukecon styles

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#25]
Adopt keycloak pages to dukecon styles and layouts: https://keycloak.github.io/docs/userguide/keycloak-server/html/themes.html
- @ascheman: find out how to apply themes to server
- @steffchep: adopt themes

theme should be lightweight for mobile clients and fit into flex clients also (check with @chrisdutz)

**Comment by dasniko** [comment]
I could support here, not really an effort...
Only login/forgot pwd screen (not much effort), or also other screens as well (e.g. account application - a bit more effort)?
Do you already have some screens/examples of layout?

**Comment by dasniko** [comment]
@ascheman To deploy the themes to the KC server, you just have to provide a folder under `.../standalone/configuration/themes/` besides the already existing ones. Then, you have to select the appropriate theme in the realm settings.

Because of that, I suggest to realize this in the `keycloak_postgres_https` project, then it's easy to copy the folder to the docker image.

**Comment by dasniko** [comment]
This issue was moved to dukecon/keycloak_postgres_https#1
