### ISSUE TITLE
Fix Filters + "Table" heads to a top of page?

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#41]
Maybe we have discussed this already?

It would be nice if we could fix the "meta navigation", i.e., the filter list (or filter button in responsive design) and the "day selection" to the top/top left corner of the screen. Otherwise one has to scroll back to the top of the page every now and then to change filter settings or select another day - in particular on mobile devices with a restricted screen size. 

For small/mobile devices it would be nice if there is only the current day tab visible and has right/left arrow navigations buttons (kind of arrows) if applicable. Example: If I have the tuesday active I would like to see a left arrow to navigate to monday and a right arrow to navigate to wednesday. If monday is active, of course there should be only the right arrow to switch to tuesday.

Can we get something like this for release 1.2?

**Comment by ascheman** [comment]
Seems the second part will be handled in #46 ...

**Comment by steffchep** [comment]
One problem I see if we "fix" the filters: There are quite a few of them, and if they are fixed in position you won't be able to get to the lower ones.
I'm also not a fan of too many individually scrollable areas. I think it is better to do one or both of the following:
- place another "days" tab at the bottom of the list
- put a "Back to Top" jump mark inside each hour slot

Thoughts?

**Comment by steffchep** [comment]
If this is (for now enough) we can close this, as I don' think actually fixing the filters in place will add to the usability....

**Comment by annam002** [comment]
Jo, you can leave it like this.
